### PR TITLE
Change the mycroft dataset format

### PR DESCRIPTION
**Pull request by rishubil**
I don't know why, but the format of the Mycroft dataset seems to be different from the format provided by Mimic Recording Studio.

I've rewritten the mycroft_dataset function based on [audio recordings format](https://github.com/MycroftAI/mimic-recording-studio#audio-recordings).

### CODE REVIEW

**Comment by JarbasAl** [comment]
I believe this mycroft dataset refers to the private Alan Pope voice dataset, which was made for the mimic1 engine

**Comment by synesthesiam** [comment]
This refers to the format used in Mycroft Recording Studio, not a specific dataset.

**Comment by rishubil** [comment]
I'm not sure if I understand the context correctly.

Do you mean that the dataset mentioned in readme is not the one generated by the latest version of Mimic Recording Studio, but the one created by the mimic1 engine?

If so, I think it would be better to change the wording in the readme to make it clearer.

**Comment by synesthesiam** [comment]
Thanks!

**Pull request merged**
