### PR TITLE
ONNX streaming support

### PR DESCRIPTION
**Pull request by mush42**
## Link to issue number:

Issue #25

### Summary of the issue:

Piper uses sentence-level streaming.

For short sentences, the latency of Piper output is relatively low due to the good RTF. But for longer sentences, latency is prohibitively high, which hinders realtime usage applications, such as with screen readers.

### Description of how this pull request fixes the issue:

This PR implements streaming output by splitting the VITS model  into two parts: encoder and decoder.

First the encoder output is generated for the whole utterance at once, then the encoder output is splitted into chunks of frames using the given chunk size and fed to the decoder chunk by chunk.

To maintain speech quality, each fed chunk is padded with some frames from the previous and next chunk, and then the corresponding wave frames are removed from the final audio output.

To export a checkpoint, use the command:

```bash
python3 -m piper_train.export_onnx_streaming CHECKPOINT_PATH ONNX_OUTPUT_DIR
```

For inference, use the command:

```python
cat input.json | python3 -m piper_train.infer_onnx_streaming --encoder ENCODER_ONNX_PATH --decoder DECODER_ONNX_PATH
```

Which pipes wave bytes to `stdout`. You can then redirect the output to any wave playing program.

### Testing performed:

Tested export and inference using hfc-male checkpoint.

### Known issues with pull request:

The encoder has many components, which can be included in the decoder to further reduce latency, but including those components in the decoder impacts naturalness. There is a trade off to be made between encoder inference speed (latency) and naturalness of generated speech.

For instance, the `flow` component can be included in the encoder or the decoder. When included in the encoder, it adds significant latency to the encoder. At the same time, chunking the input to the `flow` component (as a part of the decoder) impacts the speech quality (not verified).

We need to empirically determine which components can be made streamable, and which ones should generate their output at once.

### CODE REVIEW

**Comment by mush42** [comment]
@synesthesiam 
There is a living implementation for this in [piper-rs repo](https://github.com/mush42/piper-rs).

Do you feel positive about merging this?

Best
Musharraf

**Comment by mush42** [comment]
@synesthesiam 
I think this is ready for merging.

**Comment by marty1885** [comment]
@mush42 How do I get `input.json`? I've been trying to generate phoneme IDs manually. But I get no output (0 length in `stream`). Can you provide an example?

**Comment by eeejay** [comment]
I don't fully understand everything in this pull request, but I have a feeling that this approach can be used to implement word tracking since the sub-sentence phonemes can be synthesized in chunks. It would be cool if the stream API would be available through a `PiperVoice`.

**Comment by mush42** [comment]
@eeejay 
Phoneme duration is a better option for word tracking.

**Comment by jaredhagel2** [comment]
The Python torch library used to stream the real-time format Piper voice is large. Our device has limited storage available. Are there any plans on modifying the main piper executable to support streaming these real-time format Piper voices?

**Comment by marty1885** [comment]
I built [paroli](https://github.com/marty1885/paroli) and muse42 has his [sonata](https://github.com/mush42/sonata). Both supporting streaming mode Piper models.

**Comment by jaredhagel2** [comment]
Thanks for this @marty1885! These look great!

**Comment by mush42** [comment]
@marty1885 
BTW I watched the video of your streaming implementation. It can be even better if you apply a window function to each chunk to smooth out abrupt changes at chunk boundaries.

**Comment by marty1885** [comment]
@mush42 That's already done. The gap you hear is from the WS JS thread not being RT.

**Comment by mush42** [comment]
@marty1885 OK I understand.

**Comment by mush42** [comment]
@marty1885
That's actually very cool. I'll take a look and port your approach to Sonata.
I'm glad I brought it up.

**Comment by jaredhagel2** [comment]
Would there be value (or is it even feasible) to merge Paroli into Piper? I thought this would be easier than merging Sonata into Piper since Paroli is written in C++. Just an idea from someone who would love to learn a lot more about Paroli, Piper and Sonata (so take with a grain of salt...)

**Comment by jaredhagel2** [comment]
It see a status that states 'This pull request was closed'. I don't have much information in github when this was done. Was this done recently? Is there information on who or why the pull request was closed?

**Comment by mush42** [comment]
@jaredhagel2 this PR has been merged into Piper as an example of how to implement streaming support. Not implemented in the C++ app though.

**Comment by jaredhagel2** [comment]
Oh I see. Thank you for the clarification.

**Pull request merged**
